/**
 * Cyber Twin Attack Path Identification & Isolation Utility
 *
 * Provides deterministic logic to identify adversary progression:
 * Patient Zero (Initial Compromise / Ingress) -> Pivots (Lateral Movement / Relays) -> Target (Exfiltration / Asset Access)
 *
 * Functions:
 * - isAttackEvent(event): Classifies whether a single event belongs to the adversary progression.
 * - getAttackPathEventIds(events): Extracts list of attack-path event IDs.
 * - getAttackPathNodeIds(events, model): Extracts all entity IDs involved in the attack path.
 * - getAttackPathEdgeIds(events, model): Extracts all relationship IDs generated by attack events.
 * - identifyAttackPath(modelOrEvents): Generates complete analysis of attack vs. benign path elements.
 */

/**
 * Determines whether a BackendEvent belongs to the adversary attack path.
 * Generic and deterministic; evaluates explicit flags and domain semantics.
 *
 * @param {Object} event - BackendEvent candidate
 * @returns {boolean}
 */
export function isAttackEvent(event) {
  if (!event || typeof event !== 'object') return false;

  // 1. Explicit attack/threat classification flags if present
  if (
    event.is_attack_path === true ||
    event.is_attack === true ||
    event.attack_path === true ||
    event.threat === true ||
    event.classification === 'malicious' ||
    event.classification === 'suspicious' ||
    event.classification === 'compromised'
  ) {
    return true;
  }

  // Explicit benign classification flags
  if (
    event.is_attack_path === false ||
    event.is_benign === true ||
    event.classification === 'benign' ||
    event.classification === 'normal'
  ) {
    return false;
  }

  const type = (event.event_type || '').toLowerCase();

  // 2. Normal / Benign event types (prefixes and standard baseline operations)
  if (
    type.startsWith('normal_') ||
    type.startsWith('benign_') ||
    type.startsWith('routine_') ||
    type.startsWith('baseline_') ||
    type.startsWith('health_') ||
    type.startsWith('system_health')
  ) {
    return false;
  }

  // 3. Primary Adversary Progression Event Types
  // Compromise, unauthorized access, execution, privilege escalation, dumping, exfiltration
  if (
    type.includes('suspicious') ||
    type.includes('malicious') ||
    type.includes('unauthorized') ||
    type.includes('attack') ||
    type.includes('exfil') ||
    type.includes('exploit') ||
    type.includes('escalat') ||
    type.includes('payload') ||
    type.includes('dump') ||
    type.includes('rootkit') ||
    type.includes('backdoor') ||
    type.includes('ransom') ||
    type.includes('lateral') ||
    type.includes('c2') ||
    type.includes('command_and_control')
  ) {
    return true;
  }

  // 4. File-based attack indicators (scripts, executables, confidential data, exfiltration archives)
  const file = (event.file || '').toLowerCase();
  if (
    file.includes('payload') ||
    file.includes('exploit') ||
    file.includes('rootkit') ||
    file.includes('exfil') ||
    file.includes('confidential') ||
    file.endsWith('.ps1') ||
    file.endsWith('.sh') ||
    file.endsWith('.ko') ||
    file.endsWith('.enc') ||
    file.endsWith('.zip')
  ) {
    return true;
  }

  // 5. Pivots and Target Operations: Lateral Movement, Egress, Data Transfers, Server Connections
  if (
    type.includes('server_connection') ||
    type.includes('external_connection') ||
    type.includes('data_transfer') ||
    type.includes('transfer') ||
    type.includes('pivot')
  ) {
    return true;
  }

  // 6. Sensitive file access during incident
  if (type.includes('file_access') || type.includes('file_read') || type.includes('file_write')) {
    return true;
  }

  // Default to false for unrecognized non-malicious background events
  return false;
}

/**
 * Extracts array of event IDs that belong to the attack path.
 *
 * @param {Array<Object>} events
 * @returns {Array<string>}
 */
export function getAttackPathEventIds(events) {
  if (!Array.isArray(events)) return [];
  return events.filter(isAttackEvent).map(e => e.event_id).filter(Boolean);
}

/**
 * Extracts all unique entity IDs (nodes) involved in the attack path.
 *
 * @param {Array<Object>} events
 * @param {Object} [model] - Optional CyberTwinDataModel
 * @returns {Array<string>}
 */
export function getAttackPathNodeIds(events, model) {
  const evts = Array.isArray(events) ? events : (model?.events || []);
  const attackEventIds = new Set(getAttackPathEventIds(evts));

  if (model && Array.isArray(model.entities)) {
    return model.entities
      .filter(entity => {
        const entEvents = entity.event_ids || [];
        return entEvents.some(id => attackEventIds.has(id));
      })
      .map(entity => entity.id);
  }

  // Fallback: derive directly from events if model is not provided
  const nodeSet = new Set();
  for (const evt of evts) {
    if (attackEventIds.has(evt.event_id)) {
      if (evt.user) nodeSet.add(`user:${evt.user}`);
      if (evt.device) nodeSet.add(`device:${evt.device}`);
      if (evt.source_ip) nodeSet.add(`ip:${evt.source_ip}`);
      if (evt.destination_ip) nodeSet.add(`ip:${evt.destination_ip}`);
      if (evt.file) nodeSet.add(`file:${evt.file}`);
      if (evt.server) nodeSet.add(`server:${evt.server}`);
    }
  }
  return Array.from(nodeSet);
}

/**
 * Extracts all relationship IDs (edges) generated by events on the attack path.
 *
 * @param {Array<Object>} events
 * @param {Object} [model] - Optional CyberTwinDataModel
 * @returns {Array<string>}
 */
export function getAttackPathEdgeIds(events, model) {
  if (!model || !Array.isArray(model.relationships)) return [];
  const evts = Array.isArray(events) ? events : (model.events || []);
  const attackEventIds = new Set(getAttackPathEventIds(evts));

  return model.relationships
    .filter(rel => attackEventIds.has(rel.event_id))
    .map(rel => rel.id);
}

/**
 * Analyzes a model or event list and returns a comprehensive attack path report.
 *
 * @param {Object|Array<Object>} modelOrEvents
 * @returns {Object}
 */
export function identifyAttackPath(modelOrEvents) {
  const isModel = modelOrEvents && Array.isArray(modelOrEvents.events);
  const events = isModel ? modelOrEvents.events : (Array.isArray(modelOrEvents) ? modelOrEvents : []);
  const model = isModel ? modelOrEvents : null;

  const attackEventIds = getAttackPathEventIds(events);
  const attackEventSet = new Set(attackEventIds);

  const benignEventIds = events
    .filter(e => !attackEventSet.has(e.event_id))
    .map(e => e.event_id);

  const attackNodeIds = getAttackPathNodeIds(events, model);
  const attackNodeSet = new Set(attackNodeIds);

  const allNodeIds = model && Array.isArray(model.entities)
    ? model.entities.map(e => e.id)
    : attackNodeIds;
  const benignNodeIds = allNodeIds.filter(id => !attackNodeSet.has(id));

  const attackEdgeIds = getAttackPathEdgeIds(events, model);
  const attackEdgeSet = new Set(attackEdgeIds);

  const allEdgeIds = model && Array.isArray(model.relationships)
    ? model.relationships.map(r => r.id)
    : attackEdgeIds;
  const benignEdgeIds = allEdgeIds.filter(id => !attackEdgeSet.has(id));

  return {
    attackEventIds,
    benignEventIds,
    attackNodeIds,
    benignNodeIds,
    attackEdgeIds,
    benignEdgeIds,
    summary: {
      totalEvents: events.length,
      attackEventsCount: attackEventIds.length,
      benignEventsCount: benignEventIds.length,
      totalNodes: allNodeIds.length,
      attackNodesCount: attackNodeIds.length,
      benignNodesCount: benignNodeIds.length,
      totalEdges: allEdgeIds.length,
      attackEdgesCount: attackEdgeIds.length,
      benignEdgesCount: benignEdgeIds.length
    }
  };
}

export default {
  isAttackEvent,
  getAttackPathEventIds,
  getAttackPathNodeIds,
  getAttackPathEdgeIds,
  identifyAttackPath
};
